export const normalPatterns = [
  {
    pattern: '001',
    '3%': 'Ultimate Lepic Stabilizer',
    '6%': 'Final Masterpiece Tube',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Piercing Light Tube', "Nazeistra's Devotion Blueprint"],
    open: 'Kingston\nGrand Square\nReactor',
    from: 'Kingston\nFallen Theater\nOutpost',
  },
  {
    pattern: '002',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Afterglow Sword Polymer',
    '15%': "Greg's Reversed Fate Fiber",
    '38%': ['Smithereens Fiber', 'Gley Code'],
    open: 'Interception\nGrave Walker',
    from: 'Kingston\nInfiltration\nMagister Lab',
  },
  {
    pattern: '003',
    '3%': 'Jayber Enhanced Cells',
    '6%': 'Enzo Enhanced Cells',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Albion Cavalry Gun Tube', "Nazeistra's Devotion Polymer"],
    open: 'Interception\nGrave Walker',
    from: 'Kingston\nInfiltration\nSlumber Valley',
  },
  {
    pattern: '004',
    '3%': 'Secret Garden Tube',
    '6%': 'Viessa Enhanced Cells',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Lepic Stabilizer', 'Wave of Light Polymer'],
    open: 'Interception\nGrave Walker',
    from: 'Kingston\nSpecial\nDefense',
  },
  {
    pattern: '005',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Executor Tube',
    '15%': 'Ajax Enhanced Cells',
    '38%': ['Python Fiber', 'Final Masterpiece Polymer'],
    open: 'Interception\nGrave Walker',
    from: 'Kingston\nSpecial\nDefense',
  },
  {
    pattern: '006',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Ultimate Lepic Spiral Catalyst',
    '15%': 'Smithereens Blueprint',
    '38%': ['Restored Relic Polymer', 'Valby Code'],
    open: 'Sterile Land\nRockfall\nReactor',
    from: 'Sterile Land\nRockfall\nOutpost',
  },
  {
    pattern: '007',
    '3%': 'Kyle Code',
    '6%': 'Python Tube',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ["Nazeistra's Devotion Polymer", 'Albion Cavalry Gun Blueprint'],
    open: 'Sterile Land\nRepository\nReactor',
    from: 'Sterile Land\nRepository\nOutpost',
  },
  {
    pattern: '008',
    '3%': 'Energy Activator Blueprint',
    '6%': "King's Guard Lance Polymer",
    '15%': "Greg's Reversed Fate Polymer",
    '38%': ['Viessa Spiral Catalyst', 'Piercing Light Polymer'],
    open: 'Sterile Land\nRestricted Zone\nReactor',
    from: 'Sterile Land\nClassified Area\nOutpost',
  },
  {
    pattern: '009',
    '3%': 'Ultimate Bunny Enhanced Cells',
    '6%': "King's Guard Lance Fiber",
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Valby Spiral Catalyst', 'Python Fiber'],
    open: 'Interception\nStunning Beauty',
    from: 'Sterile Land\nInfiltration\nThe Forgottense',
  },
  {
    pattern: '010',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Blue Beetle Polymer',
    '15%': 'Lepic Spiral Catalyst',
    '38%': ["Nazeistra's Devotion Blueprint", 'Divine Punishment Fiber'],
    open: 'Interception\nStunning Beauty',
    from: 'Sterile Land\nInfiltration\nUnknown Laboratory',
  },
  {
    pattern: '011',
    '3%': 'Perforator Polymer',
    '6%': 'Divine Punishment Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Enzo Spiral Catalyst', 'Final Masterpiece Tube'],
    open: 'Interception\nStunning Beauty',
    from: 'Sterile Land\nSpecial\nKuiper Mining',
    vaulted: true,
  },
  {
    pattern: '011',
    variant: 'Mutant AA',
    '3%': 'Ultimate Valby Enhanced Cells',
    '6%': 'Divine Punishment Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Enzo Spiral Catalyst', 'Final Masterpiece Tube'],
    open: 'Interception\nStunning Beauty',
    from: 'Sterile Land\nSpecial\nKuiper Mining',
  },
  {
    pattern: '012',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Enduring Legacy Fiber',
    '15%': 'Lepic Enhanced Cells',
    '38%': ["Greg's Reversed Fate Blueprint", 'Gley Enhanced Cells'],
    open: 'Interception\nStunning Beauty',
    from: 'Sterile Land\nSpecial\nKuiper Mining',
  },
  {
    pattern: '013',
    '3%': 'Lepic Code',
    '6%': 'Gley Stabilizer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ["King's Guard Lance Fiber", 'Final Masterpiece Fiber'],
    open: 'Vespers\nRuins\nReactor',
    from: 'Vespers\nLumber Yard\nOutpost',
  },
  {
    pattern: '014',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Perforator Blueprint',
    '15%': 'Divine Punishment Blueprint',
    '38%': ['Viessa Stabilizer', 'Smithereens Tube'],
    open: 'Vespers\nLost Supply Depot\nReactor',
    from: 'Vespers\nLost Supply Depot\nOutpost',
  },
  {
    pattern: '015',
    '3%': 'Esiemo Spiral Catalyst',
    '6%': 'Restored Relic Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Albion Cavalry Gun Tube', "Nazeistra's Devotion Tube"],
    open: 'Vespers\nMoonlight Lake\nReactor',
    from: 'Vespers\nMoonlight Lake\nOutpost',
    vaulted: true,
  },
  {
    pattern: '015',
    variant: 'Mutant AA',
    '3%': 'Esiemo Spiral Catalyst',
    '6%': 'Restored Relic Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Luna Spiral Catalyst Catalyst', "Nazeistra's Devotion Tube"],
    open: 'Vespers\nMoonlight Lake\nReactor',
    from: 'Vespers\nMoonlight Lake\nOutpost',
  },
  {
    pattern: '016',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Secret Garden Polymer',
    '15%': 'Wave of Light Fiber',
    '38%': ['Albion Cavalry Gun Polymer', 'Valby Enhnaced Cells'],
    open: 'Interception\nExecutioner',
    from: 'Vespers\nInfiltration\nSepulcher',
  },
  {
    pattern: '017',
    '3%': 'Ultimate Bunny Spiral Catalyst',
    '6%': 'Kyle Stabilizer',
    '15%': 'Cystrallization Catalyst',
    '38%': ["Nazeistra's Devotion Fiber", 'Smithereens Blueprint'],
    open: 'Interception\nExecutioner',
    from: 'Vespers\nInfiltration\nThe Shelter',
    vaulted: true,
  },
  {
    pattern: '017',
    variant: 'Mutant AA',
    '3%': 'Ultimate Bunny Spiral Catalyst',
    '6%': 'Kyle Stabilizer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Luna Enhanced Cells', 'Smithereens Blueprint'],
    open: 'Interception\nExecutioner',
    from: 'Vespers\nInfiltration\nThe Shelter',
  },
  {
    pattern: '018',
    '3%': 'Perforator Synthetic Fiber',
    '6%': 'Viessa Code',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Final Masterpiece Blueprint', "Greg's Reversed Fate Tube"],
    open: 'Interception\nExecutioner',
    from: 'Vespers\nSpecial\nVoid Experiement',
  },
  {
    pattern: '019',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Ajax Code',
    '15%': 'Piercing Light Blueprint',
    '38%': ['Blue Beetle Tube', 'Lepic Stabilizer'],
    open: 'Interception\nExecutioner',
    from: 'Vespers\nSpecial\nVoid Experiement',
  },
  {
    pattern: '020',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Executor Fiber',
    '15%': 'Restored Relic Fiber',
    '38%': ['Valby Stabilizer', 'Albion Cavalry Gun Fiber'],
    open: 'Echo Swamp\nMuskeg Swamp\nReactor',
    from: 'Echo Swamp\nMuskeg Swamp\nOutpost',
    vaulted: true,
  },
  {
    pattern: '020',
    variant: 'Mutant AA',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Luna Stabilizer',
    '15%': 'Restored Relic Fiber',
    '38%': ['Valby Stabilizer', 'Albion Cavalry Gun Fiber'],
    open: 'Echo Swamp\nMuskeg Swamp Reactor',
    from: 'Echo Swamp\nMuskeg Swamp\nOutpost',
  },
  {
    pattern: '021',
    '3%': 'Ultimate Lepic Code',
    '6%': 'Piercing Light Fiber',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ["Nazeistra's Devotion Fiber", 'Enzo Spiral Catalyst'],
    open: 'Echo Swamp\nDerelict Covert\nReactor',
    from: 'Echo Swamp\nDerelict Covert\nOutpost',
  },
  {
    pattern: '022',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Esiemo Enhanced Cells',
    '15%': 'Divine Punishment Tube',
    '38%': ["Nazeistra's Tube", 'Smithereens Tube'],
    open: 'Interception\nDead Bride',
    from: 'Echo Swamp\nInfiltration\nSeed Vault',
  },
  {
    pattern: '023',
    '3%': 'Blue Beetle Blueprint',
    '6%': 'Valby Spiral Catalyst',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Restored Relic Tube', "Greg's Reversed Fate Fiber"],
    open: 'Interception\nDead Bride',
    from: 'Echo Swamp\nInfiltration\nThe Chapel',
    vaulted: true,
  },
  {
    pattern: '023',
    variant: 'Mutant AA',
    '3%': 'Blue Beetle Blueprint',
    '6%': 'Ultimate Valby Spiral Catalyst',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Restored Relic Tube', "Greg's Reversed Fate"],
    open: 'Interception\nDead Bride',
    from: 'Echo Swamp\nInfiltration\nThe Chapel',
  },
  {
    pattern: '024',
    '3%': 'Ultimateimate Bunny Stabilizer',
    '6%': 'Viessa Stabilizer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Smithereens Fiber', "Nazeistra's Devotion Blueprint"],
    open: 'Interception\nDead Bride',
    from: 'Echo Swamp\nSpecial\nDefense',
  },
  {
    pattern: '025',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Python Blueprint',
    '15%': 'Blue Beetle Synthetic Fiber',
    '38%': ['Enzo Code', "Nazeistra's Devotion Fiber"],
    open: 'Interception\nDead Bride',
    from: 'Echo Swamp\nSpecial\nDefense',
  },
  {
    pattern: '026',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Ultimate Lepic Enhanced Cells',
    '15%': 'Afterglow Sword Fiber',
    '38%': ['Blue Beetle Tube', 'Valby Spiral Catalyst'],
    open: 'Agna Desert\nVermillion Waste\nReactor',
    from: 'Agna Desert\nVermillion Waste\nOutpost',
  },
  {
    pattern: '027',
    '3%': 'Perforator Fiber',
    '6%': 'Smithereens Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Ajax Enhanced Cells', 'Albion Cavalry Gun Polymer'],
    open: 'Agna Desert\nStorage Outpost\nReactor',
    from: 'Agna Desert\nStorage Outpost\nOutpost',
    vaulted: true,
  },
  {
    pattern: '027',
    variant: 'Mutant AA',
    '3%': 'Luna Code',
    '6%': 'Smithereens Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Ajax Enhanced Cells', 'Albion Cavalry Gun Polymer'],
    open: 'Agna Desert\nStorage Outpost\nReactor',
    from: 'Agna Desert\nStorage Outpost\nOutpost',
  },
  {
    pattern: '028',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Gley Spiral Catalyst',
    '15%': "Greg's Reversed Fate Tube",
    '38%': ['Smithereens Blueprint', 'Enzo Enhanced Cells'],
    open: 'Agna Desert\nMiragestone\nReactor',
    from: 'Agna Desert\nMiragestone\nOutpost',
  },
  {
    pattern: '029',
    '3%': 'Secret Garden Fiber',
    '6%': 'Python Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Valby Stabilizer', "Greg's Reversed Fate Polymer"],
    open: 'Interception\nDevourer',
    from: 'Agna Desert\nInfiltration\nThe Asylum',
  },
  {
    pattern: '030',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Clairvoyance Fiber',
    '15%': 'Viessa Code',
    '38%': ['Albion Cavalry Gun Fiber', 'Final Masterpiece Blueprint'],
    open: 'Interception\nDevourer',
    from: 'Agna Desert\nInfiltration\nCaligo Ossuary',
    vaulted: true,
  },
  {
    pattern: '030',
    variant: 'Mutant AA',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Ultimate Valby Stabilizer',
    '15%': 'Viessa Code',
    '38%': ['Albion Cavalry Gun Fiber', 'Final Masterpiece Blueprint'],
    open: 'Interception\nDevourer',
    from: 'Agna Desert\nInfiltration\nCaligo Ossuary',
  },
  {
    pattern: '031',
    '3%': 'Ajax Spiral Catalyst',
    '6%': 'Executor Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Final Masterpiece Blueprint', 'Albion Cavalry Gun Blueprint'],
    open: 'Interception\nDevourer',
    from: 'Agna Desert\nSpecial\nVoid Experiement',
  },
  {
    pattern: '032',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Wave of Light Blueprint',
    '15%': 'Secret Garden Blueprint',
    '38%': ['Valby Code', 'Restored Relic Tube'],
    open: 'Interception\nDevourer',
    from: 'Agna Desert\nSpecial\nVoid Experiement',
  },
  {
    pattern: '033',
    '3%': 'Yujin Spiral Catalyst',
    '6%': 'Restored Relic Blueprint',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Valby Enhanced Cells', 'Piercing Light Polymer'],
    open: 'White-Night Gulch\nMountaintops\nReactor',
    from: 'White-Night Gulch\nMountaintops\nOutpost',
  },
  {
    pattern: '034',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Secret Garden Polymer',
    '15%': 'Final Masterpiece Polymer',
    '38%': ["Greg's Reversed Fate Fiber", 'Viessa Enhanced Cells'],
    open: 'White-Night Gulch\nObservatory\nReactor',
    from: 'White-Night Gulch\nShipment\nOutpost',
  },
  {
    pattern: '035',
    '3%': 'Ultimate Ajax Enhanced Cells',
    '6%': 'Blue Beetle Fiber',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Enzo Code', "King's Guard Lance Tube"],
    open: 'White-Night Gulch\nHatchery\nReactor',
    from: 'White-Night Gulch\nHatchery\nOutpost',
  },
  {
    pattern: '036',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Executor Tube',
    '15%': 'Valby Code',
    '38%': ['Divine Punishment Tube', 'Smithereens Polymer'],
    open: 'Interception\nPyromaniac',
    from: "White-Night Gulch\nInfiltration\nMystery's End",
  },
  {
    pattern: '037',
    '3%': 'Executor Blueprint',
    '6%': 'Albion Cavalry Gun Blueprint',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Restored Relic Fiber', 'Enzo Spiral Catalyst Catalyst'],
    open: 'Interception\nPyromaniac',
    from: 'White-Night Gulch\nInfiltration\nBio-Lab',
  },
  {
    pattern: '038',
    '3%': 'Ultimate Viessa Code',
    '6%': 'Perforator Tube',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Divine Punishment Polymer', 'Smithereens Fiber'],
    open: 'Interception\nPyromaniac',
    from: 'White-Night Gulch\nSpecial\nKuiper Mining',
    vaulted: true,
  },
  {
    pattern: '038',
    variant: 'Mutant AA',
    '3%': 'Ultimate Viessa Code',
    '6%': 'Perforator Tube',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Divine Punishment Polymer', 'Luna Enhanced Cells'],
    open: 'Interception\nPyromaniac',
    from: 'White-Night Gulch\nSpecial\nKuiper Mining',
  },
  {
    pattern: '039',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Clairvoyance Fiber',
    '15%': 'Python Tube',
    '38%': ['Enzo Stabilizer', 'Wave of Light Tube'],
    open: 'Interception\nPyromaniac',
    from: 'White-Night Gulch\nSpecial\nKuiper Mining',
  },
  {
    pattern: '040',
    '3%': 'Energy Activator Blueprint',
    '6%': "King's Guard Lance Blueprint",
    '15%': 'Piercing Light Tube',
    '38%': ['Restored Relic Polymer', 'Enzo Stabilizer'],
    open: 'Hagios\nDune Base\nReactor',
    from: 'Hagios\nDune Base\nOutpost',
  },
  {
    pattern: '041',
    '3%': 'Kyle Enhanced Cells',
    '6%': 'Clairvoyance Tube',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ["Nazeistra's Devotion Polymer", 'Restored Relic Fiber'],
    open: 'Hagios\nCorrupted Zone\nReactor',
    from: 'Hagios\nCorrupted Zone\nOutpost',
  },
  {
    pattern: '042',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Blue Beetle Polymer',
    '15%': 'Albion Cavalry Gun Fiber',
    '38%': ['Valby Stabilizer', 'Final Masterpiece Fiber'],
    open: 'Hagios\nFractured Monolith\nReactor',
    from: 'Hagios\nForward base\nOutpost',
  },
  {
    pattern: '043',
    '3%': 'Ultimate Viessa Stabilizer',
    '6%': 'Lepic Spiral Catalyst',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Albion Cavalry Gun Tube', 'Restored Relic Blueprint'],
    open: 'Interception\nSwamp Walker',
    from: 'Hagios\nInfiltration\nThe Haven',
  },
  {
    pattern: '044',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Jayber Stabilizer',
    '15%': 'Python Polymer',
    '38%': ['Final Masterpiece Polymer', "Greg's Reversed Fate Blueprint"],
    open: 'Interception\nSwamp Walker',
    from: 'Hagios\nInfiltration\nOld Mystery',
    vaulted: true,
  },
  {
    pattern: '044',
    variant: 'Mutant AA',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Ultimate Valby Enhanced Cells',
    '15%': 'Python Polymer',
    '38%': ['Final Masterpiece Polymer', "Greg's Reversed Fate Blueprint"],
    open: 'Interception\nSwamp Walker',
    from: 'Hagios\nInfiltration\nOld Mystery',
  },
  {
    pattern: '045',
    '3%': 'Yujin Enhanced Cells',
    '6%': 'Jayber Spiral Catalyst',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ["King's Guard Lance Tube", "Greg's Reversed Fate Polymer"],
    open: 'Interception\nSwamp Walker',
    from: 'Hagios\nSpecial\nVoid Experiement',
  },
  {
    pattern: '046',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Executor Fiber',
    '15%': 'Divine Punishment Blueprint',
    '38%': ['Restored Relic Tube', 'Viessa Spiral Catalyst'],
    open: 'Interception\nSwamp Walker',
    from: 'Hagios\nSpecial\nVoid Experiement',
  },
  {
    pattern: '047',
    '3%': 'Jayber Code',
    '6%': 'Smithereens Polymer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Gley Stabilizer', 'Piercing Light Blueprint'],
    open: 'Fortress\nFrozen Valley\nReactor',
    from: 'Fortress\nFrozen Valley\nOutpost',
  },
  {
    pattern: '048',
    '3%': 'Energy Activator Blueprint',
    '6%': "King's Guard Lance Polymer",
    '15%': 'Divine Punishment Fiber',
    '38%': ['Wave of Light Polymer', 'Valby Enhanced Cells'],
    open: 'Fortress\nFallen Ark\nReactor',
    from: 'Fortress\nConverter Facility\nOutpost',
  },
  {
    pattern: '049',
    '3%': 'Perforator Polymer',
    '6%': 'Ajax Stabilizer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ["Greg's Reversed Fate Blueprint", 'Restored Relic Blueprint'],
    open: 'Fortress\nDefense Line\nReactor',
    from: 'Fortress\nDefense Line\nOutpost',
    vaulted: true,
  },
  {
    pattern: '049',
    variant: 'Mutant AA',
    '3%': 'Perforator Polymer',
    '6%': 'Ajax Stabilizer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ["Greg's Reversed Fate Blueprint", 'Luna Spiral Catalyst'],
    open: 'Fortress\nDefense Line\nReactor',
    from: 'Fortress\nDefense Line\nOutpost',
  },
  {
    pattern: '050',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Gley Spiral Catalyst',
    '15%': 'Enzo Enhanced Cells',
    '38%': ["Nazeistra's Devotion Tube", 'Final Masterpiece Tube'],
    open: 'Interception\nHanged Man',
    from: 'Fortress\nInfiltration\nQuarantine Zone',
  },
  {
    pattern: '051',
    '3%': 'Clairvoyance Polymer',
    '6%': 'Enzo Stabilizer',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Albion Cavalry Gun Polymer', "Greg's Reversed Fate Tube"],
    open: 'Interception\nHanged Man',
    from: 'Fortress\nInfiltration\nHeart Of The Fortress',
  },
  {
    pattern: '052',
    '3%': 'Ultimate Bunny Code',
    '6%': 'Smithereens Tube',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Wave of Light Tube', 'Final Masterpiece Fiber'],
    open: 'Interception\nHanged Man',
    from: 'Fortress\nSpecial\nDefense',
    vaulted: true,
  },
  {
    pattern: '052',
    variant: 'Mutant AA',
    '3%': 'Ultimate Bunny Code',
    '6%': 'Ultimate Valby Spiral Catalyst',
    '15%': 'Crystallization Catalyst Blueprint',
    '38%': ['Wave of Light Tube', 'Final Masterpiece Fiber'],
    open: 'Interception\nHanged Man',
    from: 'Fortress\nSpecial\nDefense',
  },
  {
    pattern: '053',
    '3%': 'Energy Activator Blueprint',
    '6%': 'Enduring Legacy Tube',
    '15%': 'Piercing Light Fiber',
    '38%': ['Enzo Code', 'Gley Enhanced Cells'],
    open: 'Interception\nHanged Man',
    from: 'Fortress\nSpecial\nDefense',
  },
] as const;

export const hardPatterns = [
  {
    pattern: '054',
    '6%': 'Esiemo Code',
    '10%': 'Kyle Enhanced Cells',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Python Polymer', 'Secret Garden Blueprint'],
    open: 'Kingston\nGrand Square\nReactor',
    from: 'Kingston\nFallen Theater\nOutpost',
  },
  {
    pattern: '055',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Kyle Spiral Catalyst',
    '20%': 'Jayber Enhanced Cells',
    '32%': ['Executor Blueprint', 'Afterglow Sword Fiber'],
    open: 'Kingston\nGrand Square\nReactor',
    from: 'Kingston\nFallen Theater\nOutpost',
    vaulted: true,
  },
  {
    pattern: '055',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Kyle Spiral Catalyst',
    '20%': 'Jayber Enhanced Cells',
    '32%': ['Executor Blueprint', 'Ultimate Valby Stabilizer'],
    open: 'Kingston\nGrand Square\nReactor',
    from: 'Kingston\nFallen Theater\nOutpost',
  },
  {
    pattern: '056',
    '6%': 'Ultimate Viessa Enhanced Cells',
    '10%': 'Afterglow Sword Tube',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Lepic Stabilizer', 'Smithereens Blueprint'],
    open: 'Interception\nExecutioner',
    from: 'Kingston\nInfiltration\nMagister Lab',
  },
  {
    pattern: '057',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Ajax Enhanced Cells',
    '20%': 'Yujin Spiral Catalyst',
    '32%': ["King's Guard Lance Blueprint", 'Clairvoyance Polymer'],
    open: 'Interception\nExecutioner',
    from: 'Kingston\nInfiltration\nMagister Lab',
  },
  {
    pattern: '058',
    '6%': 'Ultimate Gley Code',
    '10%': 'Clairvoyance Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Kyle Stabilizer', 'Piercing Light Tube'],
    open: 'Interception\nExecutioner',
    from: 'Kingston\nInfiltration\nSlumber Valley',
  },
  {
    pattern: '059',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Enduring Legacy Blueprint',
    '20%': 'Ultimate Lepic Stabilizer',
    '32%': ['Python Tube', 'Esiemo Enhanced Cells'],
    open: 'Interception\nExecutioner',
    from: 'Kingston\nInfiltration\nSlumber Valley',
  },
  {
    pattern: '060',
    '6%': 'Ultimate Gley Enhanced Cells',
    '10%': 'Perforator Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Ajax Enhanced Cells', 'Clairvoyance Tube'],
    open: 'Sterile Land\nRockfall\nReactor',
    from: 'Sterile Land\nRockfall\nOutpost',
  },
  {
    pattern: '061',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Lepic Code',
    '20%': 'Esiemo Spiral Catalyst',
    '32%': ['Secret Garden Fiber', "Nazeistra's Devotion Polymer"],
    open: 'Sterile Land\nRockfall\nReactor',
    from: 'Sterile Land\nRockfall\nOutpost',
  },
  {
    pattern: '062',
    '6%': 'Ultimate Ajax Stabilizer',
    '10%': 'Restored Relic Tube',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Afterglow Sword Polymer', 'Jayber Stabilizer'],
    open: 'Sterile Land\nRepository\nReactor',
    from: 'Sterile Land\nRepository\nOutpost',
  },
  {
    pattern: '063',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Valby Code',
    '20%': 'Kyle Enhanced Cells',
    '32%': ['Wave of Light Fiber', 'Python Blueprint'],
    open: 'Sterile Land\nRepository\nReactor',
    from: 'Sterile Land\nRepository\nOutpost',
  },
  {
    pattern: '064',
    '6%': 'Yujin Code',
    '10%': "Greg's Reversed Fate Blueprint",
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ["King's Guard Lance Tube", 'Lepic Enhanced Cells'],
    open: 'Sterile Land\nRestricted Zone\nReactor',
    from: 'Sterile Land\nClassified Area\nOutpost',
  },
  {
    pattern: '065',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Yujin Stabilizer',
    '20%': 'Jayber Code',
    '32%': ['Perforator Polymer', 'Enduring Legacy Tube'],
    open: 'Sterile Land\nRestricted Zone\nReactor',
    from: 'Sterile Land\nClassified Area\nOutpost',
  },
  {
    pattern: '066',
    '6%': 'Ultimate Ajax Code',
    '10%': 'Afterglow Sword Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Gley Enhanced Cells', 'Albion Cavalry Gun Fiber'],
    open: 'Interception\nDead Bride',
    from: 'Sterile Land\nInfiltration\nThe Forgottense',
  },
  {
    pattern: '067',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Esiemo Stabilizer',
    '20%': 'Ajax Spiral Catalyst',
    '32%': ['Enduring Legacy Fiber', 'Executor Polymer'],
    open: 'Interception\nDead Bride',
    from: 'Sterile Land\nInfiltration\nThe Forgottense',
  },
  {
    pattern: '068',
    '6%': 'Ultimate Gley Code',
    '10%': 'Final Masterpiece Fiber',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Wave of Light Polymer', 'Viessa Enhanced Cells'],
    open: 'Interception\nDead Bride',
    from: 'Sterile Land\nInfiltration\nUnknown Laboratory',
    vaulted: true,
  },
  {
    pattern: '068',
    variant: 'Mutant AA',
    '6%': 'Ultimate Gley Code',
    '10%': 'Final Masterpiece Fiber',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Wave of Light Polymer', 'Luna Stabilizer'],
    open: 'Interception\nDead Bride/Gluttony',
    from: 'Sterile Land\nInfiltration\nUnknown Laboratory',
  },
  {
    pattern: '069',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Lepic Spiral Catalyst',
    '20%': 'Gley Code',
    '32%': ['Perforator Fiber', 'Blue Beetle Blueprint'],
    open: 'Interception\nDead Bride',
    from: 'Sterile Land\nInfiltration\nUnknown Laboratory',
  },
  {
    pattern: '070',
    '6%': 'Ultimate Viessa Spiral Catalyst',
    '10%': 'Ajax Spiral Catalyst',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Blue Beetle Polymer', 'Executor Fiber'],
    open: 'Vespers\nRuins\nReactor',
    from: 'Vespers\nLumber Yard\nOutpost',
  },
  {
    pattern: '071',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Yujin Spiral Catalyst',
    '20%': 'Luna Spiral Catalyst Catalyst',
    '32%': ['Afterglow Sword Fiber', 'Python Blueprint'],
    open: 'Vespers\nRuins\nReactor',
    from: 'Vespers\nLumber Yard\nOutpost',
    vaulted: true,
  },
  {
    pattern: '071',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Yujin Spiral Catalyst',
    '20%': 'Luna Spiral Catalyst Catalyst',
    '32%': ['Afterglow Sword Fiber', 'Python Blueprint'],
    open: 'Vespers\nRuins\nReactor',
    from: 'Vespers\nLumber Yard\nOutpost',
  },
  {
    pattern: '072',
    '6%': 'Ultimate Gley Spiral Catalyst',
    '10%': 'Lepic Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Wave of Light Tube', "Greg's Reversed Fate Fiber"],
    open: 'Vespers\nLost Supply Depot\nReactor',
    from: 'Vespers\nSupply Depot\nOutpost',
  },
  {
    pattern: '073',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Bunny Enhanced Cells',
    '20%': 'Kyle Code',
    '32%': ['Divine Punishment Tube', 'Perforator Tube'],
    open: 'Vespers\nLost Supply Depot\nReactor',
    from: 'Vespers\nSupply Depot\nOutpost',
    vaulted: true,
  },
  {
    pattern: '073',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Bunny Enhanced Cells',
    '20%': 'Ultimate Valby Spiral Catalyst',
    '32%': ['Divine Punishment Tube', 'Perforator Tube'],
    open: 'Vespers\nLost Supply Depot\nReactor',
    from: 'Vespers\nSupply Depot\nOutpost',
  },
  {
    pattern: '074',
    '6%': 'Esiemo Code',
    '10%': 'Secret Garden Tube',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Ultimate Lepic Enhanced Cells', 'Piercing Light Blueprint'],
    open: 'Vespers\nMoonlight Lake\nReactor',
    from: 'Vespers\nMoonlight Lake\nOutpost',
  },
  {
    pattern: '075',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Viessa Code',
    '20%': 'Ajax Code',
    '32%': ["Nazeistra's Devotion Tube", "King's Guard Lance Fiber"],
    open: 'Vespers\nMoonlight Lake\nReactor',
    from: 'Vespers\nMoonlight Lake\nOutpost',
  },
  {
    pattern: '076',
    '6%': 'Ultimate Gley Stabilizer',
    '10%': 'Enduring Legacy Polymer',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Wave of Light Blueprint', 'Kyle Stabilizer'],
    open: 'Interception\nDevourer',
    from: 'Sepulcher\nInfiltration\nSepulcher',
  },
  {
    pattern: '077',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Esiemo Stabilizer',
    '20%': 'Ultimate Lepic Enhanced Cells',
    '32%': ['Executor Polymer', 'Blue Beetle Fiber'],
    open: 'Interception\nDevourer',
    from: 'Sepulcher\nInfiltration\nSepulcher',
  },
  {
    pattern: '078',
    '6%': 'Ultimate Ajax Code',
    '10%': 'Smithereens Polymer',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Gley Spiral Catalyst', 'Enduring Legacy Fiber'],
    open: 'Interception\nDevourer',
    from: 'Shelter\nInfiltration\nShelter',
  },
  {
    pattern: '079',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Yujin Stabilizer',
    '20%': 'Afterglow Sword Blueprint',
    '32%': ['Lepic Spiral Catalyst', 'Albion Cavalry Gun Polymer'],
    open: 'Interception\nDevourer',
    from: 'Shelter\nInfiltration\nShelter',
  },
  {
    pattern: '080',
    '6%': 'Yujin Code',
    '10%': 'Perforator Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Lepic Enhanced Cells', 'Executor Tube'],
    open: 'Echo Swamp\nMuskeg Swamp\nReactor',
    from: 'Echo Swamp\nMuskeg Swamp\nOutpost',
  },
  {
    pattern: '081',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Esiemo Stabilizer',
    '20%': 'Afterglow Sword Tube',
    '32%': ['Enzo Stabilizer', "King's Guard Lance Polymer"],
    open: 'Echo Swamp\nMuskeg Swamp\nReactor',
    from: 'Echo Swamp\nMuskeg Swamp\nOutpost',
    vaulted: true,
  },
  {
    pattern: '081',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Luna Enhanced Cells',
    '20%': 'Afterglow Sword Tube',
    '32%': ['Enzo Stabilizer', "King's Guard Lance Polymer"],
    open: 'Echo Swamp\nMuskeg Swamp\nReactor',
    from: 'Echo Swamp\nMuskeg Swamp\nOutpost',
  },
  {
    pattern: '082',
    '6%': 'Ultimate Bunny Code',
    '10%': 'Kyle Enhanced Cells',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Secret Garden Polymer', 'Executor Blueprint'],
    open: 'Echo Swamp\nDerelict Covert\nReactor',
    from: 'Echo Swamp\nDerelict Covert\nOutpost',
  },
  {
    pattern: '083',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Viessa Code',
    '20%': 'Enduring Legacy Polymer',
    '32%': ['Gley Stabilizer', 'Albion Cavalry Gun Blueprint'],
    open: 'Echo Swamp\nDerelict Covert\nReactor',
    from: 'Echo Swamp\nDerelict Covert\nOutpost',
  },
  {
    pattern: '084',
    '6%': 'Ultimate Gley Enhanced Cells',
    '10%': 'Clairvoyance Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Viessa Spiral Catalyst', 'Divine Punishment Polymer'],
    open: 'Interception\nPyromaniac',
    from: 'Echo Swamp\nInfiltration\nSeed Vault',
  },
  {
    pattern: '085',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Lepic Spiral Catalyst',
    '20%': 'Yujin Enhanced Cells',
    '32%': ['Secret Garden Blueprint', 'Smithereens Fiber'],
    open: 'Interception\nPyromaniac',
    from: 'Echo Swamp\nInfiltration\nSeed Vault',
  },
  {
    pattern: '086',
    '6%': 'Ultimate Viessa Enhanced Cells',
    '10%': 'Valby Stabilizer',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Blue Beetle Blueprint', 'Restored Relic Blueprint'],
    open: 'Interception\nPyromaniac',
    from: 'Echo Swamp\nInfiltration\nThe Chapel',
  },
  {
    pattern: '087',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Kyle Spiral Catalyst',
    '20%': 'Ultimate Bunny Spiral Catalyst',
    '32%': ['Wave of Light Blueprint', 'Enduring Legacy Tube'],
    open: 'Interception\nPyromaniac',
    from: 'Echo Swamp\nInfiltration\nThe Chapel',
    vaulted: true,
  },
  {
    pattern: '087',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Valby Code',
    '20%': 'Ultimate Bunny Spiral Catalyst',
    '32%': ['Wave of Light Blueprint', 'Enduring Legacy Tube'],
    open: 'Interception\nPyromaniac',
    from: 'Echo Swamp\nInfiltration\nThe Chapel',
  },
  {
    pattern: '088',
    '6%': 'Ultimate Ajax Code',
    '10%': 'Secret Garden Tube',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Ajax Stabilizer', 'Python Polymer'],
    open: 'Agna Desert\nVermillion Waste\nReactor',
    from: 'Agna Desert\nVermillion Waste\nOutpost',
  },
  {
    pattern: '089',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Lepic Code',
    '20%': 'Jayber Spiral Catalyst',
    '32%': ['Afterglow Sword Fiber', 'Divine Punishment Blueprint'],
    open: 'Agna Desert\nVermillion Waste\nReactor',
    from: 'Agna Desert\nVermillion Waste\nOutpost',
  },
  {
    pattern: '090',
    '6%': 'Esiemo Code',
    '10%': 'Yujin Enhanced Cells',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Executor Tube', "King's Guard Lance Polymer"],
    open: 'Agna Desert\nStorage Outpost\nReactor',
    from: 'Agna Desert\nStorage Outpost\nOutpost',
    vaulted: true,
  },
  {
    pattern: '090',
    variant: 'Mutant AA',
    '6%': 'Esiemo Code',
    '10%': 'Luna Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Executor Tube', "King's Guard Lance Polymer"],
    open: 'Agna Desert\nStorage Outpost\nReactor',
    from: 'Agna Desert\nStorage Outpost\nOutpost',
  },
  {
    pattern: '091',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Viessa Stabilizer',
    '20%': 'Jayber Enhanced Cells',
    '32%': ['Perforator Tube', 'Piercing Light Fiber'],
    open: 'Agna Desert\nStorage Outpost\nReactor',
    from: 'Agna Desert\nStorage Outpost\nOutpost',
  },
  {
    pattern: '092',
    '6%': 'Ultimate Gley Stabilizer',
    '10%': 'Jayber Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Blue Beetle Polymer', 'Clairvoyance Tube'],
    open: 'Agna Desert\nMiragestone\nReactor',
    from: 'Agna Desert\nMiragestone\nOutpost',
  },
  {
    pattern: '093',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Enzo Code',
    '20%': 'Gley Code',
    '32%': ['Smithereens Tube', 'Wave of Light Fiber'],
    open: 'Agna Desert\nMiragestone\nReactor',
    from: 'Agna Desert\nMiragestone\nOutpost',
  },
  {
    pattern: '094',
    '6%': 'Ultimate Ajax Spiral Catalyst',
    '10%': 'Afterglow Sword Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Lepic Spiral Catalyst', 'Blue Beetle Fiber'],
    open: 'Interception\nSwamp Walker',
    from: 'Agna Desert\nInfiltration\nThe Asylum',
    vaulted: true,
  },
  {
    pattern: '094',
    variant: 'Mutant AA',
    '6%': 'Ultimate Ajax Spiral Catalyst',
    '10%': 'Afterglow Sword Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Luna Code', 'Blue Beetle Fiber'],
    open: 'Interception\nSwamp Walker, Gluttony',
    from: 'Agna Desert\nInfiltration\nThe Asylum',
  },
  {
    pattern: '095',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Yujin Stabilizer',
    '20%': 'Viessa Code',
    '32%': ['Clairvoyance Polymer', 'Divine Punishment Tube'],
    open: 'Interception\nSwamp Walker',
    from: 'Agna Desert\nInfiltration\nThe Asylum',
  },
  {
    pattern: '096',
    '6%': 'Ultimate Gley Spiral Catalyst',
    '10%': 'Ajax Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Python Fiber', 'Final Masterpiece Tube'],
    open: 'Interception\nSwamp Walker',
    from: 'Agna Desert\nInfiltration\nCaligo Ossuary',
  },
  {
    pattern: '097',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Enduring Legacy Blueprint',
    '20%': 'Enzo Enhanced Cells',
    '32%': ["King's Guard Lance Blueprint", 'Viessa Enhanced Cells'],
    open: 'Interception\nSwamp Walker',
    from: 'Agna Desert\nInfiltration\nCaligo Ossuary',
  },
  {
    pattern: '098',
    '6%': 'Ultimate Ajax Spiral Catalyst',
    '10%': 'Lepic Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Wave of Light Tube', "King's Guard Lance Tube"],
    open: 'White-Night Gulch\nMountaintops\nReactor',
    from: 'White-Night Gulch\nMountaintops\nOutpost',
    vaulted: true,
  },
  {
    pattern: '098',
    variant: 'Mutant AA',
    '6%': 'Ultimate Ajax Spiral Catalyst',
    '10%': 'Luna Stabilizer',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Wave of Light Tube', "King's Guard Lance Tube"],
    open: 'White-Night Gulch\nMountaintops\nReactor',
    from: 'White-Night Gulch\nMountaintops\nOutpost',
  },
  {
    pattern: '099',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Bunny Stabilizer',
    '20%': 'Clairvoyance Blueprint',
    '32%': ['Secret Garden Fiber', 'Gley Spiral Catalyst'],
    open: 'White-Night Gulch\nMountaintops\nReactor',
    from: 'White-Night Gulch\nMountaintops\nOutpost',
  },
  {
    pattern: '100',
    '6%': 'Yujin Code',
    '10%': 'Jayber Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Afterglow Sword Polymer', 'Executor Fiber'],
    open: 'White-Night Gulch\nObservatory\nReactor',
    from: 'White-Night Gulch\nShipment\nOutpost',
  },
  {
    pattern: '101',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Enduring Legacy Blueprint',
    '20%': 'Kyle Code',
    '32%': ['Jayber Stabilizer', 'Perforator Polymer'],
    open: 'White-Night Gulch\nObservatory\nReactor',
    from: 'White-Night Gulch\nShipment\nOutpost',
  },
  {
    pattern: '102',
    '6%': 'Ultimate Gley Spiral Catalyst',
    '10%': 'Viessa Stabilizer',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Python Tube', 'Piercing Light Blueprint'],
    open: 'White-Night Gulch\nHatchery\nReactor',
    from: 'White-Night Gulch\nHatchery\nOutpost',
  },
  {
    pattern: '103',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Esiemo Stabilizer',
    '20%': 'Ajax Code',
    '32%': ['Blue Beetle Tube', 'Divine Punishment Fiber'],
    open: 'White-Night Gulch\nHatchery\nReactor',
    from: 'White-Night Gulch\nHatchery\nOutpost',
  },
  {
    pattern: '104',
    '6%': 'Ultimate Gley Stabilizer',
    '10%': 'Enduring Legacy Polymer',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Executor Polymer', 'Esiemo Enhanced Cells'],
    open: 'Interception\nObstructer',
    from: "White-Night Gulch\nInfiltration\nMystery's End",
  },
  {
    pattern: '105',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Kyle Spiral Catalyst',
    '20%': 'Ultimate Lepic Stabilizer',
    '32%': ["Greg's Reversed Fate Polymer", 'Python Fiber'],
    open: 'Interception\nObstructer',
    from: "White-Night Gulch\nInfiltration\nMystery's End",
  },
  {
    pattern: '106',
    '6%': 'Ultimate Bunny Code',
    '10%': 'Lepic Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Piercing Light Tube', 'Clairvoyance Fiber'],
    open: 'Interception\nObstructer',
    from: 'White-Night Gulch\nInfiltration\nBio-Lab',
  },
  {
    pattern: '107',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Viessa Stabilizer',
    '20%': 'Afterglow Sword Blueprint',
    '32%': ['Ajax Stabilizer', 'Albion Cavalry Gun Tube'],
    open: 'Interception\nObstructer',
    from: 'White-Night Gulch\nInfiltration\nBio-Lab',
  },
  {
    pattern: '108',
    '6%': 'Ultimate Viessa Spiral Catalyst',
    '10%': 'Secret Garden Tube',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Lepic Enhanced Cells', "Nazeistra's Devotion Blueprint"],
    open: 'Hagios\nDune Base\nReactor',
    from: 'Hagios\nDune Base\nOutpost',
  },
  {
    pattern: '109',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Kyle Code',
    '20%': 'Esiemo Spiral Catalyst',
    '32%': ['Piercing Light Polymer', "King's Guard Lance Fiber"],
    open: 'Hagios\nDune Base\nReactor',
    from: 'Hagios\nDune Base\nOutpost',
  },
  {
    pattern: '110',
    '6%': 'Esiemo Code',
    '10%': 'Enzo Spiral Catalyst',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Clairvoyance Tube', 'Restored Relic Fiber'],
    open: 'Hagios\nCorrupted Zone\nReactor',
    from: 'Hagios\nCorrupted Zone\nOutpost',
    vaulted: true,
  },
  {
    pattern: '110',
    variant: 'Mutant AA',
    '6%': 'Ultimate Valby Code',
    '10%': 'Enzo Spiral Catalyst',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Clairvoyance Tube', 'Restored Relic Fiber'],
    open: 'Hagios\nCorrupted Zone\nReactor',
    from: 'Hagios\nCorrupted Zone\nOutpost',
  },
  {
    pattern: '111',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Yujin Stabilizer',
    '20%': 'Afterglow Sword Tube',
    '32%': ['Jayber Stabilizer', 'Enduring Legacy Tube'],
    open: 'Hagios\nCorrupted Zone\nReactor',
    from: 'Hagios\nCorrupted Zone\nOutpost',
  },
  {
    pattern: '112',
    '6%': 'Ultimate Ajax Stabilizer',
    '10%': 'Valby Spiral Catalyst',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Final Masterpiece Blueprint', 'Secret Garden Polymer'],
    open: 'Hagios\nFractured Monolith\nReactor',
    from: 'Hagios\nForward base\nOutpost',
  },
  {
    pattern: '113',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Bunny Enhanced Cells',
    '20%': 'Clairvoyance Blueprint',
    '32%': ['Perforator Tube', 'Ajax Stabilizer'],
    open: 'Hagios\nFractured Monolith\nReactor',
    from: 'Hagios\nForward base\nOutpost',
    vaulted: true,
  },
  {
    pattern: '113',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Bunny Enhanced Cells',
    '20%': 'Clairvoyance Blueprint',
    '32%': ['Perforator Tube', 'Ultimate Valby Stabilizer'],
    open: 'Hagios\nFractured Monolith\nReactor',
    from: 'Hagios\nForward base\nOutpost',
  },
  {
    pattern: '114',
    '6%': 'Ultimate Viessa Enhanced Cells',
    '10%': 'Yujin Enhanced Cells',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Secret Garden Blueprint', "Greg's Reversed Fate Tube"],
    open: 'Interception\nFrost Walker',
    from: 'Hagios\nInfiltration\nThe Haven',
  },
  {
    pattern: '115',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Viessa Stabilizer',
    '20%': 'Enduring Legacy Polymer',
    '32%': ['Gley Stabilizer', 'Wave of Light Blueprint'],
    open: 'Interception\nFrost Walker',
    from: 'Hagios\nInfiltration\nThe Haven',
    vaulted: true,
  },
  {
    pattern: '115',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Viessa Stabilizer',
    '20%': 'Enduring Legacy Polymer',
    '32%': ['Ultimate Valby Enhanced Cells', 'Wave of Light Blueprint'],
    open: 'Interception\nFrost Walker, Gluttony',
    from: 'Hagios\nInfiltration\nThe Haven',
  },
  {
    pattern: '116',
    '6%': 'Ultimate Ajax Stabilizer',
    '10%': 'Jayber Spiral Catalyst',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Divine Punishment Blueprint', 'Clairvoyance Polymer'],
    open: 'Interception\nFrost Walker',
    from: 'Hagios\nInfiltration\nOld Mystery',
  },
  {
    pattern: '117',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Bunny Stabilizer',
    '20%': 'Viessa Spiral Catalyst',
    '32%': ['Final Masterpiece Polymer', "King's Guard Lance Blueprint"],
    open: 'Interception\nFrost Walker',
    from: 'Hagios\nInfiltration\nOld Mystery',
  },
  {
    pattern: '118',
    '6%': 'Ultimate Viessa Stabilizer',
    '10%': 'Valby Enhanced Cells',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Piercing Light Polymer', "Nazeistra's Devotion Fiber"],
    open: 'Fortress\nFrozen Valley\nReactor',
    from: 'Fortress\nFrozen Valley\nOutpost',
  },
  {
    pattern: '119',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Enduring Legacy Blueprint',
    '20%': 'Jayber Enhanced Cells',
    '32%': ['Blue Beetle Tube', 'Ajax Enhanced Cells'],
    open: 'Fortress\nFrozen Valley\nReactor',
    from: 'Fortress\nFrozen Valley\nOutpost',
  },
  {
    pattern: '120',
    '6%': 'Yujin Code',
    '10%': 'Wave of Light Fiber',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Gley Enhanced Cells', 'Secret Garden Fiber'],
    open: 'Fortress\nFallen Ark\nReactor',
    from: 'Fortress\nConverter Facility\nOutpost',
  },
  {
    pattern: '121',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Ajax Enhanced Cells',
    '20%': 'Esiemo Enhanced Cells',
    '32%': ['Clairvoyance Fiber', 'Executor Blueprint'],
    open: 'Fortress\nFallen Ark\nReactor',
    from: 'Fortress\nConverter Facility\nOutpost',
  },
  {
    pattern: '122',
    '6%': 'Ultimate Gley Enhanced Cells',
    '10%': 'Perforator Blueprint',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Afterglow Sword Polymer', 'Lepic Stabilizer'],
    open: 'Fortress\nDefense Line\nReactor',
    from: 'Fortress\nDefense Line\nOutpost',
  },
  {
    pattern: '123',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Kyle Spiral Catalyst',
    '20%': 'Ultimate Bunny Spiral Catalyst',
    '32%': ['Python Blueprint', 'Divine Punishment Fiber'],
    open: 'Fortress\nDefense Line\nReactor',
    from: 'Fortress\nDefense Line\nOutpost',
  },
  {
    pattern: '124',
    '6%': 'Ultimate Ajax Spiral Catalyst',
    '10%': 'Gley Code',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Restored Relic Polymer', 'Perforator Fiber'],
    open: 'Interception\nMolten Fortress',
    from: 'Fortress\nInfiltration\nQuarantine Zone',
  },
  {
    pattern: '125',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Viessa Code',
    '20%': 'Yujin Spiral Catalyst',
    '32%': ['Piercing Light Fiber', 'Wave of Light Polymer'],
    open: 'Interception\nMolten Fortress',
    from: 'Fortress\nInfiltration\nQuarantine Zone',
    vaulted: true,
  },
  {
    pattern: '125',
    variant: 'Mutant AA',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Ultimate Viessa Code',
    '20%': 'Ultimate Valby Code',
    '32%': ['Piercing Light Fiber', 'Wave of Light Polymer'],
    open: 'Interception\nMolten Fortress, Gluttony',
    from: 'Fortress\nInfiltration\nQuarantine Zone',
  },
  {
    pattern: '126',
    '6%': 'Ultimate Gley Code',
    '10%': 'Ajax Spiral Catalyst',
    '20%': 'Crystallization Catalyst Blueprint',
    '32%': ['Divine Punishment Polymer', 'Enduring Legacy Fiber'],
    open: 'Interception\nMolten Fortress',
    from: 'Fortress\nInfiltration\nHeart Of The Fortress',
  },
  {
    pattern: '127',
    '6%': 'Energy Activator Blueprint',
    '10%': 'Esiemo Spiral Catalyst',
    '20%': 'Afterglow Sword Tube',
    '32%': ['Kyle Stabilizer', 'Blue Beetle Blueprint'],
    open: 'Interception\nMolten Fortress',
    from: 'Fortress\nInfiltration\nHeart Of The Fortress',
  },
] as const;

type Pattern = {
  pattern: string;
  open: string;
  from: string;
  vaulted?: boolean;
  variant?: string;
};

export type NormalPattern = Pattern & {
  '3%': string;
  '6%': string;
  '15%': string;
  '38%': string[];
};
export type NormalRates = keyof NormalPattern;
export type HardPattern = Pattern & {
  '6%': string;
  '10%': string;
  '20%': string;
  '32%': string[];
};
export type HardRates = keyof NormalPattern;

const commonHeaders = ['Amorphous Material Pattern', 'Dropped From', 'Opened At'] as const;
export const normalHeaders = [...commonHeaders, 3, 6, 15, 38] as const;
export const hardHeaders = [...commonHeaders, 6, 10, 20, 32] as const;
